-- Supabase Database Setup Script for ERMS
-- Copy and run this script in your Supabase SQL Editor: https://supabase.com/dashboard/project/vllipntxgdrlintgbguf/sql/new

-- 1. Drop existing tables if they exist (Caution: this deletes data)
-- IF YOU ALREADY RAN THE PREVIOUS SCRIPT, JUST RUN: ALTER TABLE teaching_aids ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
DROP TABLE IF EXISTS borrow_requests CASCADE;
DROP TABLE IF EXISTS teaching_aids CASCADE;

-- 2. Create teaching_aids table
CREATE TABLE teaching_aids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    brand TEXT,
    model TEXT,
    image_url TEXT,
    remarks TEXT,
    unit TEXT DEFAULT '具',
    category TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create borrow_requests table
CREATE TABLE borrow_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT REFERENCES teaching_aids(id) ON DELETE CASCADE,
    applicant_name TEXT NOT NULL,
    applicant_phone TEXT NOT NULL,
    applicant_emp_id TEXT NOT NULL,
    applicant_dept TEXT NOT NULL,
    applicant_email TEXT NOT NULL,
    required_date DATE NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, approved, rejected, returned
    reject_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    approved_at TIMESTAMP WITH TIME ZONE,
    returned_at TIMESTAMP WITH TIME ZONE
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE teaching_aids ENABLE ROW LEVEL SECURITY;
ALTER TABLE borrow_requests ENABLE ROW LEVEL SECURITY;

-- 5. Set up RLS Policies for teaching_aids
-- Allow public select (anyone can view teaching aids)
CREATE POLICY "Allow public read teaching aids" ON teaching_aids
    FOR SELECT USING (true);

-- Allow authenticated users (admins) to insert/update/delete
CREATE POLICY "Allow authenticated insert teaching aids" ON teaching_aids
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update teaching aids" ON teaching_aids
    FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated delete teaching aids" ON teaching_aids
    FOR DELETE USING (auth.role() = 'authenticated');

-- 6. Set up RLS Policies for borrow_requests
-- Allow public select (anyone can view borrowing status on Kanban)
CREATE POLICY "Allow public read borrow requests" ON borrow_requests
    FOR SELECT USING (true);

-- Allow public insert (anyone can apply to borrow)
CREATE POLICY "Allow public insert borrow requests" ON borrow_requests
    FOR INSERT WITH CHECK (true);

-- Allow authenticated users (admins) to update/delete (approve, reject, mark returned)
CREATE POLICY "Allow authenticated update borrow requests" ON borrow_requests
    FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated delete borrow requests" ON borrow_requests
    FOR DELETE USING (auth.role() = 'authenticated');

-- 7. Insert 36 Seed Items
INSERT INTO teaching_aids (id, name, quantity, brand, model, image_url, remarks, unit) VALUES
(1, '褥瘡/燙傷傷口模型', 2, 'Laerdal', 'VT-900', 'images/item_1.jpg', '傷口部位', '具'),
(2, '導尿管置放模型', 3, 'Laerdal', '375-21001', 'images/item_2.jpg', '可置換配件，男/女導尿均可操作', '具'),
(3, '傷口縫合模型', 7, 'Life/form', 'LF01028U', 'images/item_3.jpg', '可自行切割傷口', '具'),
(4, '氣胸訓練模型', 1, 'Laerdal', '26005001', 'images/item_4.jpg', '全身或半身', '具'),
(5, '下肢穿刺模擬訓練模型', 1, 'Laerdal', '262-00001', 'images/item_5.jpg', NULL, '具'),
(6, '脊椎穿刺模型', 1, 'Gaumard', 'S411', 'images/item_6.jpg', NULL, '具'),
(7, '氣管插管練習模型', 3, 'Laerdal', '250000', 'images/item_7.jpg', NULL, '具'),
(8, '嬰兒氣道處理訓練模型', 2, 'Laerdal', '250-00250', 'images/item_8.jpg', NULL, '具'),
(9, '鼻胃管置入練習模型', 2, 'Laerdal', '375-10001', 'images/item_9.jpg', '可做氣切', '具'),
(10, '靜脈軟針置入練習模型', 3, 'Laerdal', '270-00001', 'images/item_10.jpg', NULL, '具'),
(11, '婦科內診檢查模型 (子宮頸抹片篩檢之操作)', 2, 'KOKEN', 'LM-050', 'images/item_11.jpg', '詳列附加道具明細', '具'),
(12, '基本救命術 (BLS) 模型', 1, 'Laerdal', '310055', 'images/item_12.jpg', NULL, '具'),
(13, '簡易燈號成人半身 CPR 模型', 2, 'Prestan', 'PP-AM-100M-MS', 'images/item_13.jpg', NULL, '具'),
(14, '半身中央及週邊靜脈導管照護模型', 2, 'Laerdal', 'VT-400P', 'images/item_14.jpg', NULL, '具'),
(15, '皮下注射模型', 2, 'Life/form', 'LF01008U', 'images/item_15.jpg', NULL, '具'),
(16, '肌肉注射模型', 2, 'Nasco', 'LF01184U', 'images/item_16.jpg', NULL, '具'),
(17, '眼底鏡病變判讀模型', 1, 'Adam,Rouilly', 'AR303', 'images/item_17.jpg', NULL, '具'),
(18, '耳道病變判讀模型', 1, 'Adam,Rouilly', 'AR302', 'images/item_18.jpg', NULL, '具'),
(19, 'Mr. Hurt Trauma Head', 2, 'Laerdal', '261-02001', 'images/item_19.jpg', NULL, '具'),
(20, 'CVC 穿刺插入模擬裝置模型', 1, 'KYOTO KAGAKU', 'M93B', 'images/item_20.jpg', NULL, '具'),
(21, '半身中央靜脈訓練模型', 1, 'Laerdal', 'IV Torso', 'images/item_21.jpg', NULL, '具'),
(22, '高級心臟救命術訓練模型', 1, 'Laerdal', 'Megacode Kelly', 'images/item_22.jpg', NULL, '具'),
(23, '電子式動脈採血手臂', 2, '潗大科技', 'ARB-001', 'images/item_23.jpg', NULL, '具'),
(24, '成人呼吸音及心音聽診練習模型', 1, NULL, NULL, 'images/item_24.jpg', NULL, '具'),
(25, '嬰兒', 1, 'Laerdal', '180011', 'images/item_25.jpg', '全身/1歲', '具'),
(26, '哽塞娃娃', 1, 'Laerdal', 'Baby Anne', 'images/item_26.jpg', NULL, '具'),
(27, '簡易嬰兒 QCPR', 2, 'Laerdal', '133-01050', 'images/item_27.jpg', NULL, '具'),
(28, '新生兒急救模組', 1, 'Nasco', 'LF01420', 'images/item_28.jpg', NULL, '具'),
(29, '5 歲兒童護理假病人', 1, 'Gaumard', 'S150', 'images/item_29.jpg', NULL, '具'),
(30, '耳朵檢查模型', 1, 'KYOTO KAGAKU', 'M88', 'images/item_30.jpg', NULL, '具'),
(31, '肛門指診檢查模型', 1, NULL, 'SY-10402-PRO', 'images/item_31.jpg', NULL, '具'),
(32, '乳房觸診模型', 1, 'Gaumard/美國製', 'S230.40', 'images/item_32.jpg', NULL, '具'),
(33, '氣道處理模型', 1, 'Gaumard', 'S315', 'images/item_33.jpg', NULL, '具'),
(34, '局部麻醉超音波穿刺訓練仿體', 2, '3B', '1019637', 'images/item_34.jpg', NULL, '具'),
(35, '行動訓練監護儀', 2, 'REALITi / Nasco', NULL, 'images/item_35.jpg', NULL, '組'),
(36, '超音波影像儀', 2, 'ASUS', 'LU700', 'images/item_36.jpg', NULL, '台');

-- Reset the identity sequence to continue from 37
ALTER TABLE teaching_aids ALTER COLUMN id RESTART WITH 37;
